list:
	helm repo list

add-bitnami:
	helm repo add bitnami https://charts.bitnami.com/bitnami

search:
	helm search repo bitnami

update:
	helm repo update

install:
	helm install bitnami/mysql --generate-name

show:
	helm show chart bitnami/mysql

show-all:
	helm show all bitnami/mysql

uninstall:
	helm uninstall mysql-1764329414

create:
	helm create syamsul

linter:
	helm lint ./syamsul

