services:
  nsqlookupd-clusterip:
    image: nsqio/nsq
    command: /nsqlookupd
    hostname: nsqlookupd-clusterip
    container_name: nsqlookupd-clusterip
    ports:
      - "4160:4160" #tcp
      - "4161:4161" #http
    networks:
      - my-network

  nsqadmin-clusterip:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd-clusterip:4161
    hostname: nsqadmin-clusterip
    container_name: nsqadmin-clusterip
    depends_on:
      - nsqlookupd-clusterip  
    ports:
      - "4171:4171"
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    external: true