AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EKS Cluster

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  MyEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: my-eks-cluster
      RoleArn: !GetAtt EKSClusterRole.Arn
      Version: "1.34"
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0eb111d17198bcafb
          - subnet-09ab8991a3557fbea
          - subnet-0ef76cf997890286e
        SecurityGroupIds:
          - sg-0ced17272be198cb8

  # IAM Role for Node Group (EC2 Worker Nodes)
  NodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  MyNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref MyEKSCluster
      NodeRole: !GetAtt NodeGroupRole.Arn
      Subnets:
        - subnet-0eb111d17198bcafb
        - subnet-09ab8991a3557fbea
        - subnet-0ef76cf997890286e
      ScalingConfig:
        MinSize: 1
        MaxSize: 5
        DesiredSize: 3
      InstanceTypes:
        - t3.medium
