AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS PostgreSQL Instance using CloudFormation"

Parameters:
  DBPassword:
    Type: String
    NoEcho: true
  YourIP:
    Type: String
    Description: "Your IP (example: 123.123.123.123/32)"

Resources:

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow database access from developer IP"
      VpcId: <VPC>
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref YourIP
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS"
      SubnetIds:
        - <SUBNET_1>
        - <SUBNET_2>

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydb
      Engine: postgres
      MasterUsername: culcalcul
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: gp3
      Port: 5432

Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
