services:
    
  postgres-exporter-clusterip:
    container_name: postgres-exporter-clusterip
    hostname: postgres-exporter-clusterip
    image: quay.io/prometheuscommunity/postgres-exporter
    networks:
      - my-network
    env_file:
      - ".env"
    # ports:
    #   - "9187:9187"
    # command:
    #   - --config.file=/config.yaml
    #   - --storage.tsdb.retention.time=7d
    #   - --web.external-url=/postgres-exporter
    # volumes:
    #   - ./config.yaml:/config.yaml:ro
    # working_dir: /app
    # command: ["/bin/bash"]

  
networks:
  my-network:
    name: my-network
    external: true