#Secret
# secret value is left empty, I add it manually to ensure security
apiVersion: v1
kind: Secret
metadata:
  name: url-http-secret
stringData:
  POSTGRES_USERNAME: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres-clusterip
  POSTGRES_PORT: "5432"
  REDIS_PASSWORD: admin
  REDIS_HOST: redis-clusterip
  REDIS_PORT: "6379"
  REDIS_TTL: "300000" #in millisecond
  HASHER_LENGTH: "10"
  HASHER_CHARACTER_POOL: qQwWeErRtTyYuUiIoOpPaAsSdDfFgGhHjJkKlLzZxXcCvVbBnNmM123456
  HASHER_HOST: https://syamsul.online
  PORT: "5000"
  JAEGER_HOST: "jaeger-clusterip:4317"