---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: http-clusterip
  labels:
    app: http
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: http
    type: pod
  ports:
    - protocol: TCP
      port: 12000 # service port
      targetPort: 12000 # container port
      name: http-clusterip

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  labels:
    app: http
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
      type: pod
  template:
    metadata:
      labels:
        app: http
        type: pod
    spec:
      containers:
      - name: http
        image: syamsuldocker/http:0.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 12000
        envFrom:
          - secretRef:
              name: http-secret
        command: ["./http"]

