# --- Build stage ---
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Download deps first (cached if go.mod/go.sum unchanged)
COPY go.mod go.sum ./
RUN go mod download

# Copy source and build
COPY . .
RUN go build -o http ./binary/http

# --- Run stage ---
FROM alpine:3.20

# Install tiny libc (for DNS resolution etc.)
RUN apk add --no-cache ca-certificates

WORKDIR /root/
COPY --from=builder /app/http .

# Run app
CMD ["./http"]
