AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for Messaging"

Resources:

  # ECR Repository for Url Shortener
  WebsocketRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: websocket
      ImageScanningConfiguration:
        scanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }