AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for Messaging"
  
Parameters:
  SnsTopic:
    Type: String

Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SnsTopic
      DisplayName: !Ref SnsTopic
      # Subscription:
      #   - Protocol: email # optional
      #     Endpoint: example@example.com # optional

  # ECR Repository for Url Shortener
  WebsocketRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: websocket
      ImageScanningConfiguration:
        scanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }