// This file defines the gRPC API — the network contract between client and server.
//
// WHY DO WE NEED THIS?
//
// Right now, our Store can only be used by Go code in the same process.
// But ZooKeeper is a network service — clients connect over TCP from
// different machines. We need a way to call Create/Get/Set/Delete
// over the network.
//
// gRPC solves this:
//   Client (any language) → sends request over network → Server (our Go code)
//
// This .proto file defines:
//   1. What operations exist (Create, Get, Set, Delete, GetChildren)
//   2. What data each request contains
//   3. What data each response contains
//
// From this file, protoc generates Go code that handles all the
// serialization, networking, and connection management for us.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: zk.proto

package zkpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ZooKeeper_Create_FullMethodName      = "/zk.ZooKeeper/Create"
	ZooKeeper_Get_FullMethodName         = "/zk.ZooKeeper/Get"
	ZooKeeper_Set_FullMethodName         = "/zk.ZooKeeper/Set"
	ZooKeeper_Delete_FullMethodName      = "/zk.ZooKeeper/Delete"
	ZooKeeper_GetChildren_FullMethodName = "/zk.ZooKeeper/GetChildren"
)

// ZooKeeperClient is the client API for ZooKeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZooKeeperClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenResponse, error)
}

type zooKeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewZooKeeperClient(cc grpc.ClientConnInterface) ZooKeeperClient {
	return &zooKeeperClient{cc}
}

func (c *zooKeeperClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, ZooKeeper_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zooKeeperClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ZooKeeper_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zooKeeperClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, ZooKeeper_Set_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zooKeeperClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ZooKeeper_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zooKeeperClient) GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenResponse, error) {
	out := new(GetChildrenResponse)
	err := c.cc.Invoke(ctx, ZooKeeper_GetChildren_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZooKeeperServer is the server API for ZooKeeper service.
// All implementations must embed UnimplementedZooKeeperServer
// for forward compatibility
type ZooKeeperServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenResponse, error)
	mustEmbedUnimplementedZooKeeperServer()
}

// UnimplementedZooKeeperServer must be embedded to have forward compatible implementations.
type UnimplementedZooKeeperServer struct {
}

func (UnimplementedZooKeeperServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedZooKeeperServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedZooKeeperServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedZooKeeperServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedZooKeeperServer) GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildren not implemented")
}
func (UnimplementedZooKeeperServer) mustEmbedUnimplementedZooKeeperServer() {}

// UnsafeZooKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZooKeeperServer will
// result in compilation errors.
type UnsafeZooKeeperServer interface {
	mustEmbedUnimplementedZooKeeperServer()
}

func RegisterZooKeeperServer(s grpc.ServiceRegistrar, srv ZooKeeperServer) {
	s.RegisterService(&ZooKeeper_ServiceDesc, srv)
}

func _ZooKeeper_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooKeeperServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZooKeeper_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooKeeperServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZooKeeper_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooKeeperServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZooKeeper_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooKeeperServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZooKeeper_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooKeeperServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZooKeeper_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooKeeperServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZooKeeper_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooKeeperServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZooKeeper_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooKeeperServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZooKeeper_GetChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooKeeperServer).GetChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZooKeeper_GetChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooKeeperServer).GetChildren(ctx, req.(*GetChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZooKeeper_ServiceDesc is the grpc.ServiceDesc for ZooKeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZooKeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zk.ZooKeeper",
	HandlerType: (*ZooKeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ZooKeeper_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ZooKeeper_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _ZooKeeper_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ZooKeeper_Delete_Handler,
		},
		{
			MethodName: "GetChildren",
			Handler:    _ZooKeeper_GetChildren_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zk.proto",
}
