services:
    
  message-http-clusterip:
    container_name: message-http-clusterip
    hostname: message-http-clusterip
    image: message-http
    ports:
      - "10000:10000" # can be closed for security
    env_file:
      - ".env"
    networks:
      - my-network
    working_dir: /app
    volumes:
      - .env:/app/.env
      - ./main:/app/main
    command: ["./main"]

  
networks:
  my-network:
    name: my-network
    external: true