
---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip
  labels:
    app: postgres
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: postgres
    type: pod
  ports:
    - protocol: TCP
      port: 5432 # service port
      targetPort: 5432 # container port


---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      type: pod
  template:
    metadata:
      labels:
        app: postgres
        type: pod
    spec:
      containers:
      - name: postgres
        image: postgres:16.3
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: postgres-secret

