services:
    
  prometheus-clusterip:
    container_name: prometheus-clusterip
    hostname: prometheus-clusterip
    image: prom/prometheus
    ports:
      - "9090:9090" # ui
    networks:
      - my-network
    volumes:
      - ./config.yaml:/config.yaml:ro
    command:
      - --config.file=/config.yaml
      - --storage.tsdb.retention.time=7d
      - --web.external-url=/prometheus
    # env_file:
    #   - ".env"
    # working_dir: /app
    # command: ["/bin/bash"]

  
networks:
  my-network:
    name: my-network
    external: true