-- Enable UUID generation (gen_random_uuid)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS url_shortener (
    -- Primary key generated by Postgres to guarantee uniqueness
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    short VARCHAR(255) UNIQUE NOT NULL,
    long VARCHAR(2048) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index on short column for faster lookups
CREATE INDEX IF NOT EXISTS idx_url_shortener_short ON url_shortener(short);

-- Index on long column for faster duplicate checks
CREATE INDEX IF NOT EXISTS idx_url_shortener_long ON url_shortener(long);
