AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS PostgreSQL Instance using CloudFormation"

Parameters:
  DBPassword:
    Type: String
    NoEcho: true

  DBUsername:
    Type: String
    NoEcho: true

Resources:

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow database access from developer IP"
      VpcId: vpc-08780a8b5fb9266e8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: "172.31.0.0/16"
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS"
      SubnetIds:
        - subnet-0eb111d17198bcafb
        - subnet-09ab8991a3557fbea
        - subnet-0ef76cf997890286e

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: postgres
      Engine: postgres
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      DBInstanceClass: db.t3.medium
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: gp3
      Port: 5432

Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
