apiVersion: v1
kind: Secret
metadata:
  name: graph-http-secret
stringData:
  PORT: "7000"
  JAEGER_HOST: "jaeger-clusterip:4317"

---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: graph-http-clusterip
  labels:
    app: graph-http
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: graph-http
    type: pod
  ports:
    - protocol: TCP
      port: 7000 # service port
      targetPort: 7000 # container port
      name: graph-http-clusterip

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-http-deployment
  labels:
    app: graph-http
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-http
      type: pod
  template:
    metadata:
      labels:
        app: graph-http
        type: pod
    spec:
      containers:
      - name: graph-http
        image: syamsuldocker/graph-http:0.0.10
        ports:
        - containerPort: 7000
        # env:
        #   - name: POSTGRES_USER
        #     value: admin
        #   - name: POSTGRES_PASSWORD
        #     value: admin
        envFrom:
          - secretRef:
              name: graph-http-secret
        command: ["./main"]
        # - configMapRef:
        #     name: postgres-configmap

#Secret
# secret value is left empty, I add it manually to ensure security
# apiVersion: v1
# kind: Secret
# metadata:
#   name: graph-http-secret
# stringData:
#   POSTGRES_USERNAME:
#   POSTGRES_PASSWORD:
#   POSTGRES_DB:
#   POSTGRES_HOST:
#   POSTGRES_PORT:
#   REDIS_PASSWORD:
#   REDIS_HOST:
#   REDIS_PORT:
#   REDIS_TTL:
#   HASHER_LENGTH:
#   HASHER_CHARACTER_POOL:
#   HASHER_HOST:
#   PORT:

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-configmap
# data:
#   POSTGRES_USER: 
#   POSTGRES_PASSWORD: 

---
# nodeport, can be closed for better security
# leave it open for debug purpose
# apiVersion: v1
# kind: Service
# metadata:
#   name: graph-http-nodeport
#   labels:
#     app: graph-http
#     type: nodeport
# spec:
#   type: NodePort
#   selector:
#     app: graph-http
#     type: pod
#   ports:
#     - protocol: TCP
#       port: 5000 #container port
#       targetPort: 5000 #service port
#       nodePort: 30002 #open port
#       name: graph-http-nodeport