apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "syamsul.online"
    - "jaeger.syamsul.online"
    - "prometheus.syamsul.online"
    - "url.syamsul.online"
    - "kiali.syamsul.online"
    - "graph.syamsul.online"
    - "grafana.syamsul.online"

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: app-vs
spec:
  hosts:
  - "syamsul.online"
  - "jaeger.syamsul.online"
  - "prometheus.syamsul.online"
  - "url.syamsul.online"
  - "kiali.syamsul.online"
  - "graph.syamsul.online"
  - "grafana.syamsul.online"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "url.syamsul.online"
    route:
    - destination:
        host: url-shortener
        port:
          number: 10000
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "jaeger.syamsul.online"
    route:
    - destination:
        host: jaeger
        port:
          number: 16686
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "prometheus.syamsul.online"
    route:
    - destination:
        host: prometheus
        port:
          number: 9090
  - match: # rewriting root to /kiali
    - uri:
        exact: /
      headers:
        host:
          exact: "kiali.syamsul.online"
    rewrite:
      uri: "/kiali"
    route:
    - destination:
        host: kiali
        port:
          number: 20001
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "kiali.syamsul.online"
    route:
    - destination:
        host: kiali
        port:
          number: 20001
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "graph.syamsul.online"
    route:
    - destination:
        host: graph
        port:
          number: 10000
  - match:
    - uri:
        prefix: /
      headers:
        host:
          exact: "grafana.syamsul.online"
    route:
    - destination:
        host: grafana
        port:
          number: 3000

