apiVersion: v1
kind: Secret
metadata:
  name: user-http-secret
stringData:
  POSTGRES_USERNAME: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres-clusterip
  POSTGRES_PORT: "5432"
  REDIS_PASSWORD: admin
  REDIS_HOST: redis-clusterip
  REDIS_PORT: "6379"
  REDIS_TTL: "300000" #in millisecond
  PORT: "8000"
  JAEGER_HOST: "jaeger-clusterip:4317"

---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: user-http-clusterip
  labels:
    app: user-http
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: user-http
    type: pod
  ports:
    - protocol: TCP
      port: 8000 # service port
      targetPort: 8000 # container port
      name: user-http-clusterip

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-http-deployment
  labels:
    app: user-http
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-http
      type: pod
  template:
    metadata:
      labels:
        app: user-http
        type: pod
    spec:
      containers:
      - name: user-http
        image: syamsuldocker/user-http:0.0.6
        ports:
        - containerPort: 8000
        # env:
        #   - name: POSTGRES_USER
        #     value: admin
        #   - name: POSTGRES_PASSWORD
        #     value: admin
        envFrom:
          - secretRef:
              name: user-http-secret
        command: ["./main"]
        # - configMapRef:
        #     name: postgres-configmap

#Secret
# secret value is left empty, I add it manually to ensure security
# apiVersion: v1
# kind: Secret
# metadata:
#   name: user-http-secret
# stringData:
#   POSTGRES_USERNAME:
#   POSTGRES_PASSWORD:
#   POSTGRES_DB:
#   POSTGRES_HOST:
#   POSTGRES_PORT:
#   REDIS_PASSWORD:
#   REDIS_HOST:
#   REDIS_PORT:
#   REDIS_TTL:
#   HASHER_LENGTH:
#   HASHER_CHARACTER_POOL:
#   HASHER_HOST:
#   PORT:

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-configmap
# data:
#   POSTGRES_USER: 
#   POSTGRES_PASSWORD: 

---
# nodeport, can be closed for better security
# leave it open for debug purpose
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-http-nodeport
#   labels:
#     app: user-http
#     type: nodeport
# spec:
#   type: NodePort
#   selector:
#     app: user-http
#     type: pod
#   ports:
#     - protocol: TCP
#       port: 5000 #container port
#       targetPort: 5000 #service port
#       nodePort: 30002 #open port
#       name: user-http-nodeport