---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-canary-clusterip
  labels:
    app: url-shortener-canary
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: url-shortener-canary
    type: pod
  ports:
    - protocol: TCP
      port: 10000 # service port
      targetPort: 10000 # container port
      name: url-shortener-canary-clusterip

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-canary-deployment
  labels:
    app: url-shortener-canary
    type: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener-canary
      type: pod
  template:
    metadata:
      labels:
        app: url-shortener-canary
        type: pod
    spec:
      containers:
      - name: url-shortener-canary
        image: 717420436752.dkr.ecr.ap-southeast-1.amazonaws.com/url-shortener:cabf0e8-18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10000
        envFrom:
          - configMapRef:
              name: url-shortener-env
        command: ["./main"]

