AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for Url Shortener Application including RDS, EKS, and ECR"

Parameters:
  DbPassword:
    Type: String
    NoEcho: true

  DbUsername:
    Type: String
    NoEcho: true

  VpcCidr:
    Type: String

  DynamoTableName:
    Type: String

Resources:

  # RDS PostgreSQL Instance
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow database access from developer IP"
      VpcId: vpc-08780a8b5fb9266e8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref VpcCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS"
      SubnetIds:
        - subnet-0eb111d17198bcafb
        - subnet-09ab8991a3557fbea
        - subnet-0ef76cf997890286e

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: postgres
      Engine: postgres
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      AllocatedStorage: 20
      DBInstanceClass: db.t3.medium
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: gp3
      Port: 5432


  # ECR Repository for Url Shortener
  UrlShortenerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: url-shortener
      ImageScanningConfiguration:
        scanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # DynamoDB Table for Url Shortener Cache
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName

      BillingMode: PAY_PER_REQUEST  # No capacity planning needed

      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S

      KeySchema:
        - AttributeName: identifier
          KeyType: HASH     # Partition Key

      # for index
      # GlobalSecondaryIndexes:
      #   - IndexName: pair_url_index
      #     KeySchema:
      #       - AttributeName: pair_url
      #         KeyType: HASH
      #     Projection:
      #       ProjectionType: ALL

      SSESpecification:
        SSEEnabled: true  # Server-side encryption

      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

      Tags:
        - Key: Environment
          Value: Dev
        - Key: Owner
          Value: CloudFormation


  