AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for Url Shortener Application including RDS, EKS, and ECR"

Parameters:
  EksMaxNodes:
    Type: Number
    Default: 5

  EksDesiredNodes:
    Type: Number
    Default: 3

  DbPassword:
    Type: String
    NoEcho: true

  DbUsername:
    Type: String
    NoEcho: true

  EksClusterName:
    Type: String

  VpcCidr:
    Type: String

  DynamoTableName:
    Type: String

Resources:

  # RDS PostgreSQL Instance
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow database access from developer IP"
      VpcId: vpc-08780a8b5fb9266e8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref VpcCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS"
      SubnetIds:
        - subnet-0eb111d17198bcafb
        - subnet-09ab8991a3557fbea
        - subnet-0ef76cf997890286e

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: postgres
      Engine: postgres
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      AllocatedStorage: 20
      DBInstanceClass: db.t3.medium
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: gp3
      Port: 5432


  # Kubernetes EKS Cluster
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  MyEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EksClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      Version: "1.34"
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0eb111d17198bcafb
          - subnet-09ab8991a3557fbea
          - subnet-0ef76cf997890286e
        SecurityGroupIds:
          - sg-0ced17272be198cb8

  # IAM Role for Node Group (EC2 Worker Nodes)
  NodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  MyNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref MyEKSCluster
      NodeRole: !GetAtt NodeGroupRole.Arn
      Subnets:
        - subnet-0eb111d17198bcafb
        - subnet-09ab8991a3557fbea
        - subnet-0ef76cf997890286e
      ScalingConfig:
        MinSize: 1
        MaxSize: !Ref EksMaxNodes
        DesiredSize: !Ref EksDesiredNodes
      InstanceTypes:
        - t3.medium

  # ECR Repository for Url Shortener
  UrlShortenerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: url-shortener
      ImageScanningConfiguration:
        scanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # DynamoDB Table for Url Shortener Cache
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName

      BillingMode: PAY_PER_REQUEST  # No capacity planning needed

      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S

      KeySchema:
        - AttributeName: identifier
          KeyType: HASH     # Partition Key

      # for index
      # GlobalSecondaryIndexes:
      #   - IndexName: pair_url_index
      #     KeySchema:
      #       - AttributeName: pair_url
      #         KeyType: HASH
      #     Projection:
      #       ProjectionType: ALL

      SSESpecification:
        SSEEnabled: true  # Server-side encryption

      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

      Tags:
        - Key: Environment
          Value: Dev
        - Key: Owner
          Value: CloudFormation


  