# --- Build stage ---
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy source and build
COPY . .
RUN go build main.go

# --- Run stage ---
FROM alpine:3.20

# Install tiny libc (for DNS resolution etc.)
RUN apk add --no-cache ca-certificates

WORKDIR /app
COPY --from=builder /app/main .


EXPOSE 5000

# Run app
CMD ["./main"]
