// Code generated by MockGen. DO NOT EDIT.
// Source: google.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	integration "github.com/msyamsula/portofolio/backend-app/domain/user/integration"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// GetRedirectURLGoogle mocks base method.
func (m *MockAuthService) GetRedirectURLGoogle(ctx context.Context, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedirectURLGoogle", ctx, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRedirectURLGoogle indicates an expected call of GetRedirectURLGoogle.
func (mr *MockAuthServiceMockRecorder) GetRedirectURLGoogle(ctx, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedirectURLGoogle", reflect.TypeOf((*MockAuthService)(nil).GetRedirectURLGoogle), ctx, state)
}

// GetUserDataGoogle mocks base method.
func (m *MockAuthService) GetUserDataGoogle(ctx context.Context, state, code string) (integration.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDataGoogle", ctx, state, code)
	ret0, _ := ret[0].(integration.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDataGoogle indicates an expected call of GetUserDataGoogle.
func (mr *MockAuthServiceMockRecorder) GetUserDataGoogle(ctx, state, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDataGoogle", reflect.TypeOf((*MockAuthService)(nil).GetUserDataGoogle), ctx, state, code)
}
