// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/msyamsula/portofolio/backend-app/domain/friend/dto"
)

// MockFriendService is a mock of Service interface.
type MockFriendService struct {
	ctrl     *gomock.Controller
	recorder *MockFriendServiceMockRecorder
}

// MockFriendServiceMockRecorder is the mock recorder for MockFriendService.
type MockFriendServiceMockRecorder struct {
	mock *MockFriendService
}

// NewMockFriendService creates a new mock instance.
func NewMockFriendService(ctrl *gomock.Controller) *MockFriendService {
	mock := &MockFriendService{ctrl: ctrl}
	mock.recorder = &MockFriendServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFriendService) EXPECT() *MockFriendServiceMockRecorder {
	return m.recorder
}

// AddFriend mocks base method.
func (m *MockFriendService) AddFriend(ctx context.Context, userA, userB dto.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFriend", ctx, userA, userB)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFriend indicates an expected call of AddFriend.
func (mr *MockFriendServiceMockRecorder) AddFriend(ctx, userA, userB interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFriend", reflect.TypeOf((*MockFriendService)(nil).AddFriend), ctx, userA, userB)
}

// GetFriends mocks base method.
func (m *MockFriendService) GetFriends(ctx context.Context, user dto.User) ([]dto.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFriends", ctx, user)
	ret0, _ := ret[0].([]dto.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFriends indicates an expected call of GetFriends.
func (mr *MockFriendServiceMockRecorder) GetFriends(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriends", reflect.TypeOf((*MockFriendService)(nil).GetFriends), ctx, user)
}
