// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/msyamsula/portofolio/backend-app/domain/graph/service"
)

// MockGraphService is a mock of Service interface.
type MockGraphService struct {
	ctrl     *gomock.Controller
	recorder *MockGraphServiceMockRecorder
}

// MockGraphServiceMockRecorder is the mock recorder for MockGraphService.
type MockGraphServiceMockRecorder struct {
	mock *MockGraphService
}

// NewMockGraphService creates a new mock instance.
func NewMockGraphService(ctrl *gomock.Controller) *MockGraphService {
	mock := &MockGraphService{ctrl: ctrl}
	mock.recorder = &MockGraphServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphService) EXPECT() *MockGraphServiceMockRecorder {
	return m.recorder
}

// ArticulationPointAndBridge mocks base method.
func (m *MockGraphService) ArticulationPointAndBridge(g *service.Graph) ([]string, []string, [][]string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArticulationPointAndBridge", g)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].([][]string)
	return ret0, ret1, ret2
}

// ArticulationPointAndBridge indicates an expected call of ArticulationPointAndBridge.
func (mr *MockGraphServiceMockRecorder) ArticulationPointAndBridge(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArticulationPointAndBridge", reflect.TypeOf((*MockGraphService)(nil).ArticulationPointAndBridge), g)
}

// BreadthFirstSearch mocks base method.
func (m *MockGraphService) BreadthFirstSearch(g *service.Graph) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BreadthFirstSearch", g)
	ret0, _ := ret[0].([]string)
	return ret0
}

// BreadthFirstSearch indicates an expected call of BreadthFirstSearch.
func (mr *MockGraphServiceMockRecorder) BreadthFirstSearch(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BreadthFirstSearch", reflect.TypeOf((*MockGraphService)(nil).BreadthFirstSearch), g)
}

// DepthFirstSearch mocks base method.
func (m *MockGraphService) DepthFirstSearch(g *service.Graph) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DepthFirstSearch", g)
	ret0, _ := ret[0].([]string)
	return ret0
}

// DepthFirstSearch indicates an expected call of DepthFirstSearch.
func (mr *MockGraphServiceMockRecorder) DepthFirstSearch(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DepthFirstSearch", reflect.TypeOf((*MockGraphService)(nil).DepthFirstSearch), g)
}

// DirectedAcyclicGraph mocks base method.
func (m *MockGraphService) DirectedAcyclicGraph(g *service.Graph) ([]string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectedAcyclicGraph", g)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// DirectedAcyclicGraph indicates an expected call of DirectedAcyclicGraph.
func (mr *MockGraphServiceMockRecorder) DirectedAcyclicGraph(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectedAcyclicGraph", reflect.TypeOf((*MockGraphService)(nil).DirectedAcyclicGraph), g)
}

// Eulerian mocks base method.
func (m *MockGraphService) Eulerian(g *service.Graph) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Eulerian", g)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Eulerian indicates an expected call of Eulerian.
func (mr *MockGraphServiceMockRecorder) Eulerian(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eulerian", reflect.TypeOf((*MockGraphService)(nil).Eulerian), g)
}

// IsCycle mocks base method.
func (m *MockGraphService) IsCycle(g *service.Graph) ([]string, [][]string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCycle", g)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([][]string)
	return ret0, ret1
}

// IsCycle indicates an expected call of IsCycle.
func (mr *MockGraphServiceMockRecorder) IsCycle(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCycle", reflect.TypeOf((*MockGraphService)(nil).IsCycle), g)
}

// StronglyConnectedComponents mocks base method.
func (m *MockGraphService) StronglyConnectedComponents(g *service.Graph) ([]string, [][]string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StronglyConnectedComponents", g)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].([][]string)
	return ret0, ret1
}

// StronglyConnectedComponents indicates an expected call of StronglyConnectedComponents.
func (mr *MockGraphServiceMockRecorder) StronglyConnectedComponents(g interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StronglyConnectedComponents", reflect.TypeOf((*MockGraphService)(nil).StronglyConnectedComponents), g)
}
