// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHealthcheckService is a mock of Service interface.
type MockHealthcheckService struct {
	ctrl     *gomock.Controller
	recorder *MockHealthcheckServiceMockRecorder
}

// MockHealthcheckServiceMockRecorder is the mock recorder for MockHealthcheckService.
type MockHealthcheckServiceMockRecorder struct {
	mock *MockHealthcheckService
}

// NewMockHealthcheckService creates a new mock instance.
func NewMockHealthcheckService(ctrl *gomock.Controller) *MockHealthcheckService {
	mock := &MockHealthcheckService{ctrl: ctrl}
	mock.recorder = &MockHealthcheckServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthcheckService) EXPECT() *MockHealthcheckServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthcheckService) Check(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockHealthcheckServiceMockRecorder) Check(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthcheckService)(nil).Check), ctx)
}

// Uptime mocks base method.
func (m *MockHealthcheckService) Uptime() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uptime")
	ret0, _ := ret[0].(float64)
	return ret0
}

// Uptime indicates an expected call of Uptime.
func (mr *MockHealthcheckServiceMockRecorder) Uptime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uptime", reflect.TypeOf((*MockHealthcheckService)(nil).Uptime))
}
