// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/msyamsula/portofolio/backend-app/domain/message/dto"
)

// MockMessageService is a mock of Service interface.
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService.
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance.
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// GetConversation mocks base method.
func (m *MockMessageService) GetConversation(ctx context.Context, conversationID string) ([]dto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversation", ctx, conversationID)
	ret0, _ := ret[0].([]dto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversation indicates an expected call of GetConversation.
func (mr *MockMessageServiceMockRecorder) GetConversation(ctx, conversationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversation", reflect.TypeOf((*MockMessageService)(nil).GetConversation), ctx, conversationID)
}

// InsertMessage mocks base method.
func (m *MockMessageService) InsertMessage(ctx context.Context, msg dto.Message) (dto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMessage", ctx, msg)
	ret0, _ := ret[0].(dto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMessage indicates an expected call of InsertMessage.
func (mr *MockMessageServiceMockRecorder) InsertMessage(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMessage", reflect.TypeOf((*MockMessageService)(nil).InsertMessage), ctx, msg)
}
