// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/msyamsula/portofolio/backend-app/domain/message/dto"
)

// MockMessageRepository is a mock of Repository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// GetConversation mocks base method.
func (m *MockMessageRepository) GetConversation(ctx context.Context, conversationID, table string) ([]dto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversation", ctx, conversationID, table)
	ret0, _ := ret[0].([]dto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversation indicates an expected call of GetConversation.
func (mr *MockMessageRepositoryMockRecorder) GetConversation(ctx, conversationID, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversation", reflect.TypeOf((*MockMessageRepository)(nil).GetConversation), ctx, conversationID, table)
}

// InsertMessage mocks base method.
func (m *MockMessageRepository) InsertMessage(ctx context.Context, msg dto.Message, table string) (dto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMessage", ctx, msg, table)
	ret0, _ := ret[0].(dto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMessage indicates an expected call of InsertMessage.
func (mr *MockMessageRepositoryMockRecorder) InsertMessage(ctx, msg, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMessage", reflect.TypeOf((*MockMessageRepository)(nil).InsertMessage), ctx, msg, table)
}
