// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLShortenerService is a mock of Service interface.
type MockURLShortenerService struct {
	ctrl     *gomock.Controller
	recorder *MockURLShortenerServiceMockRecorder
}

// MockURLShortenerServiceMockRecorder is the mock recorder for MockURLShortenerService.
type MockURLShortenerServiceMockRecorder struct {
	mock *MockURLShortenerService
}

// NewMockURLShortenerService creates a new mock instance.
func NewMockURLShortenerService(ctrl *gomock.Controller) *MockURLShortenerService {
	mock := &MockURLShortenerService{ctrl: ctrl}
	mock.recorder = &MockURLShortenerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLShortenerService) EXPECT() *MockURLShortenerServiceMockRecorder {
	return m.recorder
}

// Expand mocks base method.
func (m *MockURLShortenerService) Expand(ctx context.Context, shortCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expand", ctx, shortCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Expand indicates an expected call of Expand.
func (mr *MockURLShortenerServiceMockRecorder) Expand(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expand", reflect.TypeOf((*MockURLShortenerService)(nil).Expand), ctx, shortCode)
}

// Shorten mocks base method.
func (m *MockURLShortenerService) Shorten(ctx context.Context, longURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", ctx, longURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MockURLShortenerServiceMockRecorder) Shorten(ctx, longURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockURLShortenerService)(nil).Shorten), ctx, longURL)
}
