// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/msyamsula/portofolio/backend-app/domain/url-shortener/dto"
)

// MockURLShortenerRepository is a mock of Repository interface.
type MockURLShortenerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLShortenerRepositoryMockRecorder
}

// MockURLShortenerRepositoryMockRecorder is the mock recorder for MockURLShortenerRepository.
type MockURLShortenerRepositoryMockRecorder struct {
	mock *MockURLShortenerRepository
}

// NewMockURLShortenerRepository creates a new mock instance.
func NewMockURLShortenerRepository(ctrl *gomock.Controller) *MockURLShortenerRepository {
	mock := &MockURLShortenerRepository{ctrl: ctrl}
	mock.recorder = &MockURLShortenerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLShortenerRepository) EXPECT() *MockURLShortenerRepositoryMockRecorder {
	return m.recorder
}

// FindByLongURL mocks base method.
func (m *MockURLShortenerRepository) FindByLongURL(ctx context.Context, longURL string) (*dto.URLRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByLongURL", ctx, longURL)
	ret0, _ := ret[0].(*dto.URLRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByLongURL indicates an expected call of FindByLongURL.
func (mr *MockURLShortenerRepositoryMockRecorder) FindByLongURL(ctx, longURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLongURL", reflect.TypeOf((*MockURLShortenerRepository)(nil).FindByLongURL), ctx, longURL)
}

// FindByShortCode mocks base method.
func (m *MockURLShortenerRepository) FindByShortCode(ctx context.Context, shortCode string) (*dto.URLRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(*dto.URLRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortCode indicates an expected call of FindByShortCode.
func (mr *MockURLShortenerRepositoryMockRecorder) FindByShortCode(ctx, shortCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortCode", reflect.TypeOf((*MockURLShortenerRepository)(nil).FindByShortCode), ctx, shortCode)
}

// Save mocks base method.
func (m *MockURLShortenerRepository) Save(ctx context.Context, shortCode, longURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, shortCode, longURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockURLShortenerRepositoryMockRecorder) Save(ctx, shortCode, longURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockURLShortenerRepository)(nil).Save), ctx, shortCode, longURL)
}
