// Code generated by MockGen. DO NOT EDIT.
// Source: domain/url-shortener/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/msyamsula/portofolio/backend-app/domain/url-shortener/dto"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindByLongURL mocks base method.
func (m *MockRepository) FindByLongURL(ctx context.Context, longURL string) (*dto.URLRecord, error) {
		ret := m.ctrl.Call(m, "FindByLongURL", ctx, longURL)
	ret0, _ := ret[0].(*dto.URLRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByLongURL indicates an expected call of FindByLongURL.
func (mr *MockRepositoryMockRecorder) FindByLongURL(ctx, longURL interface{}) *gomock.Call {
		return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLongURL", reflect.TypeOf((*MockRepository)(nil).FindByLongURL), ctx, longURL)
}

// FindByShortCode mocks base method.
func (m *MockRepository) FindByShortCode(ctx context.Context, shortCode string) (*dto.URLRecord, error) {
		ret := m.ctrl.Call(m, "FindByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(*dto.URLRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortCode indicates an expected call of FindByShortCode.
func (mr *MockRepositoryMockRecorder) FindByShortCode(ctx, shortCode interface{}) *gomock.Call {
		return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortCode", reflect.TypeOf((*MockRepository)(nil).FindByShortCode), ctx, shortCode)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, shortCode, longURL string) error {
		ret := m.ctrl.Call(m, "Save", ctx, shortCode, longURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, shortCode, longURL interface{}) *gomock.Call {
		return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, shortCode, longURL)
}
