// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/msyamsula/portofolio/backend-app/domain/user/dto"
)

// MockUserService is a mock of Service interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetAppTokenForGoogleUser mocks base method.
func (m *MockUserService) GetAppTokenForGoogleUser(ctx context.Context, state, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppTokenForGoogleUser", ctx, state, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppTokenForGoogleUser indicates an expected call of GetAppTokenForGoogleUser.
func (mr *MockUserServiceMockRecorder) GetAppTokenForGoogleUser(ctx, state, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppTokenForGoogleUser", reflect.TypeOf((*MockUserService)(nil).GetAppTokenForGoogleUser), ctx, state, code)
}

// GetRedirectURLGoogle mocks base method.
func (m *MockUserService) GetRedirectURLGoogle(ctx context.Context, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedirectURLGoogle", ctx, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRedirectURLGoogle indicates an expected call of GetRedirectURLGoogle.
func (mr *MockUserServiceMockRecorder) GetRedirectURLGoogle(ctx, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedirectURLGoogle", reflect.TypeOf((*MockUserService)(nil).GetRedirectURLGoogle), ctx, state)
}

// ValidateToken mocks base method.
func (m *MockUserService) ValidateToken(ctx context.Context, token string) (dto.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(dto.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockUserServiceMockRecorder) ValidateToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockUserService)(nil).ValidateToken), ctx, token)
}
