package server

// This is the gRPC server — it receives requests from the network
// and forwards them to our Store.
//
// The server is thin on purpose. It does NOT contain business logic.
// Its only job is:
//   1. Receive a gRPC request (e.g. CreateRequest)
//   2. Call the corresponding Store method (e.g. store.Create)
//   3. Return the result as a gRPC response (e.g. CreateResponse)
//
// This keeps the Store testable without needing a network.

import (
	"context"
	"fmt"
	"net"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/syamsularifin/zookeeper/api/proto/zkpb"
	"github.com/syamsularifin/zookeeper/internal/store"
)

// Server implements the ZooKeeperServer gRPC interface.
type Server struct {
	// This embeds the "unimplemented" server generated by protoc.
	// It provides default "not implemented" responses for any RPCs
	// we haven't written yet. Without it, the code won't compile
	// if we add new RPCs to the proto but haven't implemented them.
	zkpb.UnimplementedZooKeeperServer

	store *store.Store
	port  int
}

// New creates a new gRPC server backed by the given Store.
func New(s *store.Store, port int) *Server {
	return &Server{
		store: s,
		port:  port,
	}
}

// Start begins listening for gRPC connections.
//
// This blocks forever (until the process is killed).
// The flow:
//   1. Listen on TCP port
//   2. Create a gRPC server
//   3. Register our implementation
//   4. Serve incoming connections
func (s *Server) Start() error {
	addr := fmt.Sprintf(":%d", s.port)

	// Listen on TCP. This reserves the port but doesn't accept connections yet.
	lis, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("failed to listen on %s: %w", addr, err)
	}

	// Create the gRPC server and register our implementation.
	grpcServer := grpc.NewServer()
	zkpb.RegisterZooKeeperServer(grpcServer, s)

	fmt.Printf("zookeeper node listening on %s\n", addr)

	// Serve blocks forever, handling incoming RPCs.
	return grpcServer.Serve(lis)
}

// --- RPC implementations ---
// Each method receives a protobuf request, calls the Store, and returns a protobuf response.
// The `context.Context` parameter carries deadlines and cancellation — we don't use it yet
// but it's required by the gRPC interface.

func (s *Server) Create(ctx context.Context, req *zkpb.CreateRequest) (*zkpb.CreateResponse, error) {
	err := s.store.Create(req.Path, req.Data)
	if err != nil {
		// Return a gRPC error with a status code.
		// codes.AlreadyExists tells the client "this node already exists"
		// which is more useful than a generic "internal error".
		return nil, status.Errorf(codes.AlreadyExists, "%v", err)
	}

	return &zkpb.CreateResponse{Path: req.Path}, nil
}

func (s *Server) Get(ctx context.Context, req *zkpb.GetRequest) (*zkpb.GetResponse, error) {
	data, err := s.store.Get(req.Path)
	if err != nil {
		return nil, status.Errorf(codes.NotFound, "%v", err)
	}

	return &zkpb.GetResponse{Data: data}, nil
}

func (s *Server) Set(ctx context.Context, req *zkpb.SetRequest) (*zkpb.SetResponse, error) {
	err := s.store.Set(req.Path, req.Data)
	if err != nil {
		return nil, status.Errorf(codes.NotFound, "%v", err)
	}

	return &zkpb.SetResponse{}, nil
}

func (s *Server) Delete(ctx context.Context, req *zkpb.DeleteRequest) (*zkpb.DeleteResponse, error) {
	err := s.store.Delete(req.Path)
	if err != nil {
		return nil, status.Errorf(codes.FailedPrecondition, "%v", err)
	}

	return &zkpb.DeleteResponse{}, nil
}

func (s *Server) GetChildren(ctx context.Context, req *zkpb.GetChildrenRequest) (*zkpb.GetChildrenResponse, error) {
	children, err := s.store.GetChildren(req.Path)
	if err != nil {
		return nil, status.Errorf(codes.NotFound, "%v", err)
	}

	return &zkpb.GetChildrenResponse{Children: children}, nil
}
