apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
stringData:
  JAEGER_HOST: "jaeger-clusterip:4317"
  LOOKUPDS: nsqlookupd-clusterip:4161
  POSTGRES_USERNAME: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres-clusterip
  POSTGRES_PORT: "5432"

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
      type: pod
  template:
    metadata:
      labels:
        app: consumer
        type: pod
    spec:
      containers:
      - name: consumer
        image: syamsuldocker/consumer:0.0.5
        envFrom:
          - secretRef:
              name: consumer-secret
        command: ["./main"]
        # ports:
        # - containerPort: 7000
        # env:
        #   - name: POSTGRES_USER
        #     value: admin
        #   - name: POSTGRES_PASSWORD
        #     value: admin
        # - configMapRef:
        #     name: postgres-configmap

#Secret
# secret value is left empty, I add it manually to ensure security
# apiVersion: v1
# kind: Secret
# metadata:
#   name: consumer-secret
# stringData:
#   POSTGRES_USERNAME:
#   POSTGRES_PASSWORD:
#   POSTGRES_DB:
#   POSTGRES_HOST:
#   POSTGRES_PORT:
#   REDIS_PASSWORD:
#   REDIS_HOST:
#   REDIS_PORT:
#   REDIS_TTL:
#   HASHER_LENGTH:
#   HASHER_CHARACTER_POOL:
#   HASHER_HOST:
#   PORT:

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-configmap
# data:
#   POSTGRES_USER: 
#   POSTGRES_PASSWORD: 

---
# nodeport, can be closed for better security
# leave it open for debug purpose
# apiVersion: v1
# kind: Service
# metadata:
#   name: consumer-nodeport
#   labels:
#     app: consumer
#     type: nodeport
# spec:
#   type: NodePort
#   selector:
#     app: consumer
#     type: pod
#   ports:
#     - protocol: TCP
#       port: 5000 #container port
#       targetPort: 5000 #service port
#       nodePort: 30002 #open port
#       name: consumer-nodeport

# ---
# # cluster IP
# apiVersion: v1
# kind: Service
# metadata:
#   name: consumer-clusterip
#   labels:
#     app: consumer
#     type: clusterip
# spec:
#   type: ClusterIP
#   selector:
#     app: consumer
#     type: pod
#   ports:
#     - protocol: TCP
#       port: 7000 # service port
#       targetPort: 7000 # container port
#       name: consumer-clusterip