---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: obs
data:
  config.yaml: |
    service:
      extensions: [jaeger_storage, jaeger_query, healthcheckv2]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_storage_exporter]
      telemetry:
        resource:
          service.name: jaeger
          
        logs:
          level: debug
        # TODO Initialize telemetry tracer once OTEL released new feature.
        # https://github.com/open-telemetry/opentelemetry-collector/issues/10663

    extensions:
      healthcheckv2:
        use_v2: true
        http:

      jaeger_query:
        storage:
          traces: some_storage
          traces_archive: another_storage
          metrics: some_metric_backends
        http:
          endpoint: 0.0.0.0:16686
        ui:
          config_file: /jaeger/config-ui.json

      jaeger_storage:
        backends:
          some_storage: 
            opensearch:
              server_urls:
                - https://${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}@opensearch:9200
              tls:
                insecure: true
              # custom_headers:
              #   Host: "my-opensearch-domain.us-east-1.es.amazonaws.com"
              #   X-Custom-Header: "custom-value"
              indices:
                index_prefix: ""
                spans:
                  date_layout: "2006-01-02"
                  rollover_frequency: "day"
                  shards: 5
                  replicas: 1
                services:
                  date_layout: "2006-01-02"
                  rollover_frequency: "day"
                  shards: 5
                  replicas: 1
                dependencies:
                  date_layout: "2006-01-02"
                  rollover_frequency: "day"
                  shards: 5
                  replicas: 1
                sampling:
                  date_layout: "2006-01-02"
                  rollover_frequency: "day"
                  shards: 5
                  replicas: 1
          another_storage:
            opensearch:
              server_urls:
                - https://${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}@opensearch:9200
              tls:
                insecure: true
              indices:
                index_prefix: "jaeger-archive"
        metric_backends:
          some_metric_backends:
            opensearch:
              server_urls:
                - https://${ELASTICSEARCH_USER}:${ELASTICSEARCH_PASSWORD}@opensearch:9200
              tls:
                insecure: true
              indices:
                index_prefix: "jaeger-metrics"


    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"

    processors:
      batch:

    exporters:
      jaeger_storage_exporter:
        trace_storage: some_storage
  config-ui.json: |
    {
      "dependencies": {
        "dagMaxNumServices": 200,
        "menuEnabled": true
      },
      "monitor": {
        "menuEnabled": true
      },
      "archiveEnabled": true,
      "tracking": {
        "gaID": "UA-000000-2",
        "trackErrors": true
      },
      "menu": [
        {
          "label": "About Jaeger",
          "items": [
            {
              "label": "GitHub",
              "url": "https://github.com/jaegertracing/jaeger"
            },
            {
              "label": "Docs",
              "url": "https://www.jaegertracing.io/docs/latest/"
            }
          ]
        }
      ],
      "search": {
        "maxLookback": {
          "label": "2 Days",
          "value": "2d"
        },
        "maxLimit": 1500
      },
      "linkPatterns": [{
        "type": "process",
        "key": "jaeger.version",
        "url": "https://github.com/jaegertracing/jaeger-client-java/releases/tag/#{jaeger.version}",
        "text": "Information about Jaeger release #{jaeger.version}"
      },
      {
        "type": "tags",
        "key": "uniqueId",
        "url": "https://mykibana.com/uniqueId=#{uniqueId}&traceId=#{trace.traceID}",
        "text": "Redirect to kibana to view log"
      },
      {
        "type": "traces",
        "url": "https://my-logs.server?from=#{startTime | add -60000000 | epoch_micros_to_date_iso}&to=#{endTime | add 60000000 | epoch_micros_to_date_iso}'",
        "text": "Redirect to kibana to view log with formatted dates"
      }],
      "traceIdDisplayLength": 20
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: obs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
        - name: jaeger-config
          configMap:
            name: jaeger-config
      containers:
        - name: jaeger
          image: cr.jaegertracing.io/jaegertracing/jaeger:2.13.0
          ports:
            - containerPort: 16686
            - containerPort: 4317
          volumeMounts:
            - name: jaeger-config
              mountPath: /jaeger
          envFrom:
            - configMapRef:
                name: jaeger-env
          args:
            - "--config=/jaeger/config.yaml"

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: obs
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
  type: ClusterIP
