FROM nginx:latest

# Copy the HTML files into the container (including index.html)
COPY ./index.html /usr/share/nginx/html/
COPY ./script.js /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/nginx.conf

# Change the ownership of the files to www-data (the user Nginx runs as)
RUN chown -R www-data:www-data /usr/share/nginx/html

# Set correct permissions for the files
RUN chmod -R 755 /usr/share/nginx/html

# Expose port 80
EXPOSE 80