# --- Build stage ---
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Copy source and build
COPY . .
RUN go build -o dummy ./aws-cloud/services/callee/main.go

# --- Run stage ---
FROM alpine:3.20

# Install tiny libc (for DNS resolution etc.)
RUN apk add --no-cache ca-certificates

WORKDIR /root/
COPY --from=builder /app/dummy .


EXPOSE 8000

# Run app
CMD ["./dummy"]
