# docker run -d --name jaeger-clusterip \
#   -e COLLECTOR_OTLP_ENABLED=true \
#   -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
#   -p 5775:5775/udp \
#   -p 6831:6831/udp \
#   -p 6832:6832/udp \
#   -p 5778:5778 \
#   -p 16686:16686 \
#   -p 14250:14250 \
#   -p 14268:14268 \
#   -p 14269:14269 \
#   -p 4317:4317 \
#   -p 4318:4318 \
#   -p 9411:9411 \
#   jaegertracing/all-in-one:1.66.0

services:
    
  jaeger-clusterip:
    container_name: jaeger-clusterip
    hostname: jaeger-clusterip
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 #http for query UI
      - 14250:14250 # accept span
      # - 14268:14268 #API sampling
      - 14269:14269 #admin port, health check = /, promotheus stryle metrics = /metrics
      - 4317:4317 #OTLP Protobuf, GRPC
      # - 4318:4318 #OTLP, HTTP
      # - 9411:9411 #ZIPKIN
    env_file:
      - ".env"
    networks:
      - my-network
    # working_dir: /app
    # volumes:
    #   - .env:/app/.env
    #   - ./main:/app/main
    # command: ["./main"]

  
networks:
  my-network:
    name: my-network
    external: true