
---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
  labels:
    app: redis
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: redis
    type: pod
  ports:
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # container port


---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      type: pod
  template:
    metadata:
      labels:
        app: redis
        type: pod
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        envFrom:
          - secretRef:
              name: redis-secret
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]

