# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: chat-server-clusterip
  labels:
    app: chat-server
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: chat-server
    type: pod
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
      name: chat-server-clusterip

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-deployment
  labels:
    app: chat-server
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server
      type: pod
  template:
    metadata:
      labels:
        app: chat-server
        type: pod
    spec:
      containers:
      - name: chat-server
        image: syamsuldocker/chat-server:0.0.2
        ports:
        - containerPort: 8080
        # env:
        #   - name: POSTGRES_USER
        #     value: admin
        #   - name: POSTGRES_PASSWORD
        #     value: admin
        # envFrom:
        #   - secretRef:
        #       name: chat-server-secret
        command: ["./main"]
        # - configMapRef:
        #     name: postgres-configmap

#Secret
# secret value is left empty, I add it manually to ensure security
# apiVersion: v1
# kind: Secret
# metadata:
#   name: chat-server-secret
# stringData:
#   POSTGRES_USERNAME:
#   POSTGRES_PASSWORD:
#   POSTGRES_DB:
#   POSTGRES_HOST:
#   POSTGRES_PORT:
#   REDIS_PASSWORD:
#   REDIS_HOST:
#   REDIS_PORT:
#   REDIS_TTL:
#   HASHER_LENGTH:
#   HASHER_CHARACTER_POOL:
#   HASHER_HOST:
#   PORT:

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-configmap
# data:
#   POSTGRES_USER: 
#   POSTGRES_PASSWORD: 

---
# nodeport, can be closed for better security
# leave it open for debug purpose
# apiVersion: v1
# kind: Service
# metadata:
#   name: chat-server-nodeport
#   labels:
#     app: chat-server
#     type: nodeport
# spec:
#   type: NodePort
#   selector:
#     app: chat-server
#     type: pod
#   ports:
#     - protocol: TCP
#       port: 5000 #container port
#       targetPort: 5000 #service port
#       nodePort: 30002 #open port
#       name: chat-server-nodeport