AWSTemplateFormatVersion: "2010-09-09"
Description: "App Tech Stack, EKS, RDS, Elasticache, DynamoDB, Networking (VPC, Private Subnet), ECR, Bastion, SQS, SNS, NATGateway"


Parameters:
  PrivateSubnetCidr1:
    Type: String

  PrivateSubnetCidr2:
    Type: String

  TheSubnetId:
    Type: String
    Default: subnet-0eb111d17198bcafb

  TheVpcId:
    Type: String
    Default: vpc-08780a8b5fb9266e8

  KeyName:
    Type: String

  EksMaxNodes:
    Type: Number
    Default: 5

  EksDesiredNodes:
    Type: Number
    Default: 3

  EksClusterName:
    Type: String

  SnsTopic:
    Type: String

  DbPassword:
    Type: String
    NoEcho: true

  DbUsername:
    Type: String
    NoEcho: true

  VpcCidr:
    Type: String

  DynamoTableName:
    Type: String

  SqsPersistenceName:
    Type: String

  SnsPersistenceTopic:
    Type: String

  
Resources:

  # Kubernetes EKS Cluster
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  MyEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EksClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      Version: "1.34"
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0eb111d17198bcafb
          - subnet-09ab8991a3557fbea
          - subnet-0ef76cf997890286e
        SecurityGroupIds:
          - sg-0ced17272be198cb8

  # IAM Role for Node Group (EC2 Worker Nodes)
  NodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  MyNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref MyEKSCluster
      NodeRole: !GetAtt NodeGroupRole.Arn
      Subnets:
        - subnet-0eb111d17198bcafb
        - subnet-09ab8991a3557fbea
        - subnet-0ef76cf997890286e
      ScalingConfig:
        MinSize: 1
        MaxSize: !Ref EksMaxNodes
        DesiredSize: !Ref EksDesiredNodes
      InstanceTypes:
        - t3.medium

  # RDS PostgreSQL Instance
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow database access from developer IP"
      VpcId: vpc-08780a8b5fb9266e8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref VpcCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS"
      SubnetIds:
        - subnet-0eb111d17198bcafb
        - subnet-09ab8991a3557fbea
        - subnet-0ef76cf997890286e

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: postgres
      Engine: postgres
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      AllocatedStorage: 20
      DBInstanceClass: db.t3.medium
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: gp3
      Port: 5432

  # DynamoDB Table for Url Shortener Cache
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName

      BillingMode: PAY_PER_REQUEST  # No capacity planning needed

      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S

      KeySchema:
        - AttributeName: identifier
          KeyType: HASH     # Partition Key

      # for index
      # GlobalSecondaryIndexes:
      #   - IndexName: pair_url_index
      #     KeySchema:
      #       - AttributeName: pair_url
      #         KeyType: HASH
      #     Projection:
      #       ProjectionType: ALL

      SSESpecification:
        SSEEnabled: true  # Server-side encryption

      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

      Tags:
        - Key: Environment
          Value: Dev
        - Key: Owner
          Value: CloudFormation

  # Websocket Adapter
  SocketTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SnsTopic
      DisplayName: !Ref SnsTopic
        # FifoTopic: true
        # ContentBasedDeduplication: true
        # Subscription:
        #   - Protocol: email # optional
        #     Endpoint: example@example.com # optional

  # Topic and Queue for persistence data management of message
  PersistenceTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SnsPersistenceTopic
      DisplayName: !Ref SnsPersistenceTopic
      # FifoTopic: true
      # ContentBasedDeduplication: true
      # Subscription:
      #   - Protocol: email # optional
      #     Endpoint: example@example.com # optional

  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref SqsPersistenceName
      # FifoQueue: true
      # ContentBasedDeduplication: true
      VisibilityTimeout: 30

  MyQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowSNSMessages
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: "sqs:SendMessage"
            Resource: !GetAtt MyQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref PersistenceTopic

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref PersistenceTopic
      Protocol: sqs
      Endpoint: !GetAtt MyQueue.Arn
      RawMessageDelivery: true

  # Bastion
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for Bastion Host"
      VpcId: vpc-08780a8b5fb9266e8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref VpcCidr

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: subnet-0eb111d17198bcafb
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      ImageId: ami-093a7f5fbae13ff67   # Amazon Linux 2 (update based on region)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y amazon-ssm-agent
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent

  # Private Subnet 
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref TheSubnetId

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TheVpcId
      CidrBlock: !Ref PrivateSubnetCidr1
      MapPublicIpOnLaunch: false
      AvailabilityZone: ap-southeast-1a

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TheVpcId
      CidrBlock: !Ref PrivateSubnetCidr2
      MapPublicIpOnLaunch: false
      AvailabilityZone: ap-southeast-1b

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref TheVpcId

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref NATGateway
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetRouteAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetRouteAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  # Redis ElasticCache
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Private subnets for Redis
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redis
      VpcId: vpc-08780a8b5fb9266e8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: !Ref VpcCidr  # Change to restrict access

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: Redis replication group
      Engine: redis
      EngineVersion: "7.0"
      CacheNodeType: "cache.t3.micro"
      AutomaticFailoverEnabled: true
      MultiAZEnabled: true
      NumNodeGroups: 1
      ReplicasPerNodeGroup: 2
      CacheSubnetGroupName: !Ref RedisSubnetGroup # subnet group must consist of at least 2 "private" subnet that live in "different" AZ
      SecurityGroupIds:
        - !Ref RedisSecurityGroup
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true

  ### neptune
  NeptuneSubnetGroup:
    Type: AWS::Neptune::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for Neptune cluster"
      DBSubnetGroupName: !Sub "${AWS::StackName}-subnetgroup"
      SubnetIds: 
        - subnet-0eb111d17198bcafb
        - subnet-09ab8991a3557fbea
        - subnet-0ef76cf997890286e

  NeptuneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for Neptune cluster - allows incoming from AllowedCidr on port"
      VpcId: vpc-08780a8b5fb9266e8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8182
          ToPort: 8182
          CidrIp: 172.31.0.0/16
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-neptune-sg"

  NeptuneDBCluster:
    Type: AWS::Neptune::DBCluster
    Properties:
      DBClusterIdentifier: !Sub "${AWS::StackName}-cluster"
      EngineVersion: 1.2.0.0
      Port: 8182
      DBSubnetGroupName: !Ref NeptuneSubnetGroup
      VpcSecurityGroupIds:
        - !Ref NeptuneSecurityGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "07:00-08:00"
      DeletionProtection: false
      EnableCloudwatchLogsExports: []
      # If you want encryption at rest, add KmsKeyId property here and set StorageEncrypted: true
      StorageEncrypted: false

  NeptuneWriter:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${AWS::StackName}-writer"
      DBInstanceClass: db.t3.medium
      DBClusterIdentifier: !Ref NeptuneDBCluster
      # PreferredAvailabilityZone: adjust if desired
      # ApplyImmediately: true

  NeptuneReader:
    Type: AWS::Neptune::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${AWS::StackName}-reader"
      DBInstanceClass: db.t3.medium
      DBClusterIdentifier: !Ref NeptuneDBCluster
  


