apiVersion: v1
kind: ConfigMap
metadata:
  name: websocket-server-configmap
data:
  JAEGER_HOST: jaeger-clusterip:4317 

---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: websocket-server-clusterip
  labels:
    app: websocket-server
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: websocket-server
    type: pod
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
      name: websocket-server-clusterip

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server-deployment
  labels:
    app: websocket-server
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
      type: pod
  template:
    metadata:
      labels:
        app: websocket-server
        type: pod
    spec:
      containers:
      - name: websocket-server
        image: syamsuldocker/websocket-server:0.0.2
        ports:
        - containerPort: 8080
        # env:
        #   - name: POSTGRES_USER
        #     value: admin
        #   - name: POSTGRES_PASSWORD
        #     value: admin
        envFrom:
          - configMapRef:
              name: websocket-server-configmap
          # - secretRef:
          #     name: websocket-server-secret
        command: 
          - node
          - server.js

#Secret
# secret value is left empty, I add it manually to ensure security
# apiVersion: v1
# kind: Secret
# metadata:
#   name: websocket-server-secret
# stringData:
#   POSTGRES_USERNAME:
#   POSTGRES_PASSWORD:
#   POSTGRES_DB:
#   POSTGRES_HOST:
#   POSTGRES_PORT:
#   REDIS_PASSWORD:
#   REDIS_HOST:
#   REDIS_PORT:
#   REDIS_TTL:
#   HASHER_LENGTH:
#   HASHER_CHARACTER_POOL:
#   HASHER_HOST:
#   PORT:

---
# nodeport, can be closed for better security
# leave it open for debug purpose
# apiVersion: v1
# kind: Service
# metadata:
#   name: websocket-server-nodeport
#   labels:
#     app: websocket-server
#     type: nodeport
# spec:
#   type: NodePort
#   selector:
#     app: websocket-server
#     type: pod
#   ports:
#     - protocol: TCP
#       port: 5000 #container port
#       targetPort: 5000 #service port
#       nodePort: 30002 #open port
#       name: websocket-server-nodeport