services:
    
  chat-server-clusterip:
    container_name: chat-server-clusterip
    hostname: chat-server-clusterip
    image: chat-server
    ports:
      - "8080:8080" # can be closed for security
    env_file:
      - ".env"
    networks:
      - my-network
    working_dir: /app
    volumes:
      - .env:/app/.env
      - ./main:/app/main
    command: ["./main"]

  
networks:
  my-network:
    name: my-network
    external: true