services:
    
  websocket-server-clusterip:
    container_name: websocket-server-clusterip
    hostname: websocket-server-clusterip
    image: websocket-server
    ports:
      - "8080:8080" # can be closed for security
    networks:
      - my-network
    working_dir: /app
    command:
      - node
      - server.js
    # env_file:
    #   - ".env"
    # volumes:
    #   - .:/app
    #   - ./main:/app/main

  
networks:
  my-network:
    name: my-network
    external: true