#Secret
# secret value is left empty, I add it manually to ensure security
# apiVersion: v1
# kind: Secret
# metadata:
#   name: redis-secret
# stringData:
#   REDIS_PASSWORD: 

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: redis-configmap
# data:
#   redis_USER: 
#   redis_PASSWORD: 

---
# nodeport, can be closed for better security
# leave it open for debug purpose
apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    app: redis
    type: nodeport
spec:
  type: NodePort
  selector:
    app: redis
    type: pod
  ports:
    - protocol: TCP
      port: 6379 #container port
      targetPort: 6379 #service port
      nodePort: 30001 #open port
      name: redis-nodeport

---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
  labels:
    app: redis
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: redis
    type: pod
  ports:
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # container port


---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      type: pod
  template:
    metadata:
      labels:
        app: redis
        type: pod
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        envFrom:
          - secretRef:
              name: redis-secret
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        # env:
        #   - name: redis_USER
        #     value: admin
        #   - name: redis_PASSWORD
        #     value: admin
        # envFrom:
        #   - secretRef:
        #       name: redis-secret
          # - configMapRef:
          #     name: redis-configmap