
services:
  redis-clusterip: # can elevate third party
    container_name: redis-clusterip
    hostname: redis-clusterip
    image: redis
    ports:
      - "6379:6379" # can be closed for security
    env_file:
      - ".env"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - my-network


networks:
  my-network:
    name: my-network
    external: true