name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract PR diff
        run: |
          git fetch origin master
          git diff origin/master...HEAD > changes.diff

      - name: Install jq
        run: sudo apt-get install jq

      - name: Call AI review API
        run: |
          DIFF_CONTENT=$(cat changes.diff | jq -Rs .)
          curl -X POST http://0.0.0.0:12000/code/review \
            -H "Content-Type: application/json" \
            -d "{\"code\": $DIFF_CONTENT}" \
            -o review.json

      - name: Post review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT=$(cat review.json | jq -r .review)
          echo "$COMMENT" | jq \
            '{body: "🤖 AI Review Summary: Please see line comments.", event: "COMMENT"} + .' \
            > github-review.json
          
          curl -X POST \
            -H "Authorization: token {token}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/msyamsula/portofolio/pulls/4/reviews \
            -d @github-review.json
