
---
# cluster IP
apiVersion: v1
kind: Service
metadata:
  name: websocket-server-clusterip
  labels:
    app: websocket-server
    type: clusterip
spec:
  type: ClusterIP
  selector:
    app: websocket-server
    type: pod
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
      name: websocket-server-clusterip

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server-deployment
  labels:
    app: websocket-server
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
      type: pod
  template:
    metadata:
      labels:
        app: websocket-server
        type: pod
    spec:
      containers:
      - name: websocket-server
        image: syamsuldocker/websocket-server:0.0.8
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: websocket-server-configmap
        command: 
          - node
          - server.js